### ISSUE TITLE
Issue uploading file: IOS + Android

### ISSUE THREAD

**Issue by valinaga** [Vydia/react-native-background-upload#32]
Hi,

I just upgraded to 3.0.0-beta and now the files doesn't seems to get to the server.
If I use in the headers `'Content-Type': 'x-www-form-urlencoded',` or nothing at all, the data does not get to the server, although the component shows the progress and completion correctly.
If I add `'Content-Type': 'multipart/form-data'` to headers, then I get an error on the server:
`Unexpected error while processing request: invalid byte sequence in UTF-8`.
I use Ruby on Rails and the service was tested successfully with a standard multipart form in html.
Any idea?
Anyone has a reference implementation of server which is actually working, to test the component?
Thanks!

**Comment by StevePotter** [comment]
Hi, I'm looking into it but won't be able to do much until this Thursday June 15.  I would really appreciate any code you could share.  In the meantime, maybe consider downgrading to a previous version that worked for you.

**Comment by ox-michaelradionov** [comment]
We had that same error on iOS a while ago with 0.1.2 version of the module. Solution was to set a header:
```
Content-Type: application/octet-stream
```

The problem is in Ruby on Rails middleware - [rack](https://github.com/rack/rack). 
It treats both `application/x-www-form-urlencoded` and `multipart/form-data` like a form data (see [here](https://github.com/rack/rack/blob/cabaa58fe6ac355623746e287475af88c9395d66/lib/rack/request.rb#L103)) and therefore tries to parse it as a regular form data(see [here](https://github.com/rack/rack/blob/cabaa58fe6ac355623746e287475af88c9395d66/lib/rack/request.rb#L334)). But the file itself is not actually sent as a form. 
We use paperclip to work with uploads and in order to get uploaded file we use the following code:

```
Paperclip::StringioAdapter.new(request.body)
```

Hope it helps!
